[tools]
cmake = '3.28'
make = '4.4'
ninja = '1.12'
python = '3.11'
usage = '2.0'

[task_config]
includes = ['scripts']

[tasks.m2ctx]
description = 'Create a context file which can be used for m2c / decomp.me'
usage = '''
arg "<c_file>" help="File from which to create context"
'''
run = 'python tools/m2ctx.py {{arg(name="c_file")}}'
alias = 'ctx'

[tasks.build]
description = 'Build Castlevania ROM'
run = "cmake --build build"
alias = 'b'
