#!/usr/bin/env bash

rm -f baserom_uncompressed.z64
rm -rf build
rm -rf assets/nisitenma_ichigo
rm -f assets/*.bin
# rm -rf asm/nonmatchings
rm -rf asm/common
rm -rf asm/data
rm -rf asm/overlay
rm -f asm/*.s
