#!/usr/bin/env bash

FUNC_NAME=${1:?[Please specify the function name to operate on.]}
PERM_DIR=${2:-perm}

rm -rf $PERM_DIR && mkdir $PERM_DIR

cp tools/settings_sample.toml $PERM_DIR/settings.toml && \
  sed -i "s/CHANGEME/$FUNC_NAME/g" $PERM_DIR/settings.toml

cp tools/compile_sample.sh $PERM_DIR/compile.sh

unzip ~/Downloads/$FUNC_NAME.zip -d $PERM_DIR && \
  mv $PERM_DIR/{code,base}.c && \
  mv $PERM_DIR/ctx.{c,h} && \
  echo -e "#include \"./ctx.h\"\n\n$(cat $PERM_DIR/base.c)" > $PERM_DIR/base.c
