/**
 * @file EDA60.c
 *
 * Contains tables used by interactuables and the different text spots.
 */

#include "A9560.h"
#include "event_flags.h"
#include "cutscene_ID.h"

/*
cv64_actor_settings_t castleWallGratingMechanism_textSpotsActorSettings_openMechanism = {
    {257, 306, 71}, CUTSCENE_INTERACTUABLES, INTERACT_ID_TEXT_72, 7, 6, DIFFICULTY_AND_SPAWN_SETTINGS_1(SPAWN_ON_ALL_DIFFICULTIES, SPAWN_SETTINGS_1), 0
};

cv64_actor_settings_t castleWallGratingMechanism_textSpotsActorSettings_mechanismOpened = {
    {257, 306, 71}, CUTSCENE_INTERACTUABLES, INTERACT_ID_TEXT_71, 7, 6, DIFFICULTY_AND_SPAWN_SETTINGS_1(SPAWN_ON_ALL_DIFFICULTIES, SPAWN_SETTINGS_1), 0
};

door_item_open_verify_struct door_item_open_verify_list[] = {
    {ITEM_ID_ARCHIVES_KEY, EVENT_FLAG_ID_VILLA_INSIDE, EVENT_FLAG_VILLA_INSIDE_GET_ARCHIVES_KEY},
    {ITEM_ID_LEFT_TOWER_KEY, EVENT_FLAG_ID_CASTLE_WALL_MAIN, EVENT_FLAG_CASTLE_WALL_GET_LEFT_TOWER_KEY},
    {ITEM_ID_STOREROOM_KEY, EVENT_FLAG_ID_VILLA_INSIDE, EVENT_FLAG_VILLA_INSIDE_GET_STOREROOM_KEY},
    {ITEM_ID_GARDEN_KEY, EVENT_FLAG_ID_VILLA_INSIDE, EVENT_FLAG_VILLA_INSIDE_GET_GARDEN_KEY},
    {ITEM_ID_COPPER_KEY, EVENT_FLAG_ID_CASTLE_CENTER_4F_AND_MAZE_GARDEN, EVENT_FLAG_CASTLE_CENTER_4F_AND_MAZE_GARDEN_GET_COPPER_KEY},
    {ITEM_ID_CHAMBER_KEY, EVENT_FLAG_ID_CASTLE_CENTER_3F, EVENT_FLAG_CASTLE_CENTER_3F_GET_CHAMBER_KEY},
    {ITEM_ID_EXECUTION_KEY, EVENT_FLAG_ID_TOWER_EXECUTION_SORCERY_DUEL_ENDING, EVENT_FLAG_TOWER_EXECUTION_SORCERY_DUEL_ENDING_GET_EXECUTION_KEY},
    {ITEM_ID_SCIENCE_KEY1, EVENT_FLAG_ID_TOWER_SCIENCE, EVENT_FLAG_TOWER_SCIENCE_GET_KEY1},
    {ITEM_ID_SCIENCE_KEY2, EVENT_FLAG_ID_TOWER_SCIENCE, EVENT_FLAG_TOWER_SCIENCE_GET_KEY2},
    {ITEM_ID_SCIENCE_KEY3, EVENT_FLAG_ID_TOWER_SCIENCE, EVENT_FLAG_TOWER_SCIENCE_GET_KEY3},
    {ITEM_ID_CLOCKTOWER_KEY1, EVENT_FLAG_ID_CLOCK_TOWER, EVENT_FLAG_CLOCK_TOWER_GET_KEY1},
    {ITEM_ID_CLOCKTOWER_KEY2, EVENT_FLAG_ID_CLOCK_TOWER, EVENT_FLAG_CLOCK_TOWER_GET_KEY2},
    {ITEM_ID_CLOCKTOWER_KEY3, EVENT_FLAG_ID_CLOCK_TOWER, EVENT_FLAG_CLOCK_TOWER_GET_KEY3}
};

cv64_actor_settings_t* castleWallGratingMechanism_textSpotsActorSettings[1][3] = {
    {
        NULL,
        &castleWallGratingMechanism_textSpotsActorSettings_openMechanism,
        &castleWallGratingMechanism_textSpotsActorSettings_mechanismOpened
    }
};
*/
